### ISSUE TITLE
pip chrome extensio \ app

### ISSUE THREAD

**Issue by craigiswayne** [craigiswayne/craigiswayne.github.com#9]
this must be a frameless app that should be a pip feature... eg... if i wanna watch something whilst im on a web page...

**Comment by craigwayne** [comment]
should cater for youtube as well

**Comment by craigwayne** [comment]
Must also add an entry into chromes right click context menu

**Comment by craigwayne** [comment]
The right click context menu must be able to send the current website into the pip extension.

**Comment by craigwayne** [comment]
And then close the current tab once transferred.
